---
###############################################################
#                   Authelia configuration                    #
###############################################################

# Miscellaneous https://www.authelia.com/configuration/miscellaneous/introduction/
theme: auto
default_redirection_url: 'https://auth.{{ env "DOMAIN" }}/'

server:
  address: 'tcp://:9091'

log:
  level: 'debug'

identity_validation:
  reset_password:
    jwt_secret: '{{ env "JWT_SECRET" }}'

# First Factor https://www.authelia.com/configuration/first-factor/file/
authentication_backend:
  file:
    path: /config/users_database.yml

# Second Factor https://www.authelia.com/configuration/second-factor/introduction/
totp:
  issuer: 'auth.{{ env "DOMAIN" }}'

# Security https://www.authelia.com/configuration/security/access-control/
access_control:
  default_policy: 'deny'
  rules:
  - domain: 'test.{{ env "DOMAIN" }}'
    policy: 'two_factor'

# Session https://www.authelia.com/configuration/session/introduction/
session:
  domain: '{{ env "DOMAIN" }}'
  secret: '{{ env "SESSION_SECRET" }}'

  # https://www.authelia.com/configuration/session/redis/
  redis:
    host: 'authelia-redis-container'
    port: 6379
#    password: '{{ env "REDIS_PASSWORD" }}'
    password: '1234'

# Storage https://www.authelia.com/configuration/storage/postgres/
storage:
  encryption_key: '{{ env "ENCRYPTION_KEY" }}'
  postgres:
    host: 'authelia-postgres-container'
    database: 'authelia'
    username: 'authelia'
    password: '{{ env "POSTGRES_PASSWORD" }}'

regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'

# SMTP Notifier https://www.authelia.com/configuration/notifications/smtp/
notifier:
  smtp:
    address: 'submissions://{{ env "SMTP_HOST" }}:587'
    username: '{{ env "SMTP_USERNAME" }}'
    password: '{{ env "SMTP_PASSWORD" }}'
    sender: '{{ env "SMTP_SENDER" }}'
