# Vagrantfile
Vagrant.configure("2") do |config|
    config.vm.box = "gusztavvargadr/windows-10"
    config.vm.hostname = "windev"
    
    # Bridge networking
    config.vm.network "public_network"
    
    config.vm.provider "virtualbox" do |vb|
      # VM resources configuration
      vb.memory = 6144
      vb.cpus = 4
      vb.name = "windows-dev-vm"
      vb.gui = true

      # Additional optimizations
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
      vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
    end

    # Sync Projects folder
    config.vm.synced_folder "../../", "/Projects", type: "virtualbox"
    
    # WinRM configuration for Ansible
    config.vm.communicator = "winrm"
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"
    config.winrm.transport = :plaintext
    config.winrm.basic_auth_only = true
    
    # Provisioning with Ansible
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.compatibility_mode = "2.0"
      ansible.become = false
      ansible.extra_vars = {
        ansible_user: "vagrant",
        ansible_password: "vagrant",
        ansible_connection: "winrm",
        ansible_winrm_transport: "basic",
        ansible_winrm_server_cert_validation: "ignore"
      }
    end
  end