services:
  sub-aggregator:
    image: ghcr.io/stone-w4tch3r/sub-aggregator:latest
    container_name: sub-aggregator-container
    restart: unless-stopped
    expose:
      - 5000
    env_file:
      - .env
    networks:
      - caddy_net

networks:
  caddy_net:
    external:
      true