Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"  # Minimal Ubuntu XFCE Desktop
  config.vm.hostname = "dodo-dev-vm"
  
  # Resources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 6144
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--vram", "128"]  # Required for GUI
  end

  # Port forwarding for SSH
  config.vm.network "forwarded_port", guest: 22, host: 2222
  
  # Sync macOS ~/Projects to VM ~/Projects
  config.vm.synced_folder "~/Projects", "/home/user-vagrant/Projects", type: "virtualbox"

  # Use Ansible for provisioning
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
  end
end
