---
- name: Configure Windows Development VM
  hosts: all
  gather_facts: true

  roles:
    - powershell_policy
    - vbox_guestadditions
    - system_settings_configuration
    - winget_packages
    - powershell_setup
    - terminal_fonts
    - windows_activation_readme
