#cloud-config
users:
  - name: dev
    groups: [sudo]
    # Use multiple methods to ensure password works
    plain_text_passwd: dev
    passwd: dev
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      # TODO automate in future
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIc66jPOUdqTt5OAAYpPy5H5Skxkinz5xEoDyV7aQE5n distrobox-key
# Enable SSH password authentication
ssh_pwauth: true

package_update: true
package_upgrade: true
packages:
  # System
  - openssh-server
  - ca-certificates
  - gnupg
  - wget
  - gpg
  - unzip
  - ripgrep
  - curl
  - apt-transport-https
  - flatpak

  # Dev/tools
  - git
  - jq
  - tree
  - build-essential
  - net-tools
  - htop
  - fd-find
  - micro
  - nodejs
  - npm
  - silversearcher-ag
  - wl-clipboard
  - neofetch
  - gh
  - ncdu
  - distrobox
  - mitmproxy
  - trash-cli

  # Apps
  - chromium

  # Desktop
  - ubuntu-desktop-minimal

  # Guest agents
  - spice-vdagent
  - spice-webdavd
  - qemu-guest-agent

write_files:
  - path: /home/dev/.config/micro/settings.json
    owner: dev:dev
    permissions: "0644"
    content: |
      {
        "clipboard": "terminal",
        "mkparents": true
      }
    defer: true
  - path: /etc/ssh/sshd_config.d/50-cloud-init.conf
    content: |
      PasswordAuthentication yes
      PubkeyAuthentication yes
      MaxSessions 10
    permissions: "0644"

growpart:
  mode: auto
  devices: ["/"]
resize_rootfs: true

runcmd:
  # Enable services
  - systemctl enable --now ssh
  - systemctl restart ssh
  - systemctl enable --now qemu-guest-agent
  - systemctl set-default graphical.target

  # Ensure password authentication works
  - echo "dev:dev" | chpasswd
  - passwd -u dev

  # Init .profile and .bashrc
  - touch /home/dev/.profile
  - touch /home/dev/.bashrc
  
  # Set micro as default editor
  - echo 'export EDITOR=micro' >> /home/dev/.bashrc
  - echo 'export EDITOR=micro' >> /home/dev/.profile
  
  # Configure alternatives system to use micro as default editor
  - update-alternatives --install /usr/bin/editor editor /usr/bin/micro 100
  - update-alternatives --set editor /usr/bin/micro

  # --- Azlux repo for broot ---
  - install -m 0755 -d /usr/share/keyrings
  - bash -c 'curl -fsSL https://azlux.fr/repo.gpg -o /usr/share/keyrings/azlux-archive-keyring.gpg'
  - bash -c 'echo "deb [signed-by=/usr/share/keyrings/azlux-archive-keyring.gpg] https://packages.azlux.fr/debian/ stable main" > /etc/apt/sources.list.d/azlux.list'

  # --- Docker official apt repo ---
  - install -m 0755 -d /etc/apt/keyrings
  - bash -c 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg'
  - chmod a+r /etc/apt/keyrings/docker.gpg
  - bash -c 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo ${UBUNTU_CODENAME:-$VERSION_CODENAME}) stable" > /etc/apt/sources.list.d/docker.list'

  # --- Warp terminal repo ---
  - wget -qO- https://releases.warp.dev/linux/keys/warp.asc | gpg --dearmor > warpdotdev.gpg
  - sudo install -D -o root -g root -m 644 warpdotdev.gpg /etc/apt/keyrings/warpdotdev.gpg
  - sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/warpdotdev.gpg] https://releases.warp.dev/linux/deb stable main" > /etc/apt/sources.list.d/warpdotdev.list'
  - rm warpdotdev.gpg
  
  # Vscodium repo
  - | 
    wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg \
      | gpg --dearmor \
      | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg
    echo 'deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg] https://download.vscodium.com/debs vscodium main' \
      | sudo tee /etc/apt/sources.list.d/vscodium.list
  
  # Mullvad
  - sudo curl -fsSLo /usr/share/keyrings/mullvad-keyring.asc https://repository.mullvad.net/deb/mullvad-keyring.asc
  - echo "deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch=$( dpkg --print-architecture )] https://repository.mullvad.net/deb/stable stable main" | sudo tee /etc/apt/sources.list.d/mullvad.list

  # Sourcegit
  - curl https://codeberg.org/api/packages/yataro/debian/repository.key | sudo tee /etc/apt/keyrings/sourcegit.asc
  - echo "deb [signed-by=/etc/apt/keyrings/sourcegit.asc, arch=amd64,arm64] https://codeberg.org/api/packages/yataro/debian generic main" | sudo tee /etc/apt/sources.list.d/sourcegit.list

  # Firefox deb
  - sudo apt remove firefox
  - sudo add-apt-repository ppa:mozillateam/ppa
  - |
    echo '
    Package: *
    Pin: release o=LP-PPA-mozillateam
    Pin-Priority: 1001

    Package: firefox
    Pin: version 1:1snap1-0ubuntu2
    Pin-Priority: -1
    ' | sudo tee /etc/apt/preferences.d/mozilla-firefox
  - |
    echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' \
      | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox

  # Install apps
  - apt-get update
  - |
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      broot \
      docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin \
      warp-terminal \
      codium \
      mullvad-vpn \
      sourcegit \
      firefox

  # Flathub
  - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  # Flatak apps
  - flatpak install  org.kde.kate --assumeyes

  # Use Docker as non-root
  - usermod -aG docker dev
  - systemctl enable --now docker

  # claude alias
  - echo 'alias claude=\"~/.claude/local/claude\"' >> '/home/dev/.bashrc'
  - echo 'alias claude=\"~/.claude/local/claude\"' >> '/home/dev/.profile'

  # Install the "br" shell function for broot (non-interactive)
  - su - dev -c 'printf "y\n" | broot --install || true'

  # Fix ownership
  - chown -R dev:dev /home/dev

  # Reboot
  - reboot
