version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: caddy-container
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddyfiles:/etc/caddy/caddyfiles
      - ./caddy_data:/data
      - ./caddy_config:/config
    env_file:
      - .env
    networks:
      - caddy_net
    depends_on:
      - facade

  facade:
    image: crccheck/hello-world:latest
    container_name: facade-container
    restart: unless-stopped
    expose:
      - "8000"
    networks:
      - caddy_net

networks:
  caddy_net:
    name: caddy_net
    driver: bridge

volumes:
  caddy_data: # This volume contains certs. Copy it when redeploying to prevent reissuing and rate limiting.
  caddy_config: # Contains dynamic configuration, if it was created in run-time. Usually not needed.

