version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - main_net

  logto:
    image: logto/logto:latest
    container_name: logto
    environment:
      - DATABASE_URL=postgres://logto_user:password@logto-db/logto
    depends_on:
      - logto-db
    networks:
      - main_net

  logto-db:
    image: postgres:13
    container_name: logto-db
    environment:
      - POSTGRES_DB=logto
      - POSTGRES_USER=logto_user
      - POSTGRES_PASSWORD=password
    volumes:
      - logto_db_data:/var/lib/postgresql/data
    networks:
      - main_net

  landing-page:
    image: nginx:latest
    container_name: landing-page
    volumes:
      - ./landing:/usr/share/nginx/html
    networks:
      - main_net

  main-page:
    image: yourorg/main-page:latest
    container_name: main-page
    environment:
      - LOGTO_URL=http://logto:3001
    networks:
      - main_net

networks:
  main_net:

volumes:
  caddy_data:
  caddy_config:
  logto_db_data: