services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres-container
    expose:
      - '${POSTGRES_PORT}'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=${LOBE_DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      internal_net:

  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-app-container
    expose:
      - '${LOBE_PORT}'
    depends_on:
      - postgresql
    environment:
      - 'DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@lobe-postgres-container:${POSTGRES_PORT}/${LOBE_DB_NAME}'
      - 'S3_ENABLE_PATH_STYLE=1'
      - 'S3_ENDPOINT=https://${MINIO_API_DOMAIN}'
      - 'S3_PUBLIC_DOMAIN=https://${MINIO_API_DOMAIN}'
    env_file:
      - .env
    restart: unless-stopped
    networks:
      caddy_net:
      internal_net:
  
networks:
  caddy_net:
    external: true
  internal_net:

volumes:
  data:
    driver: local
  s3_data:
    driver: local
