---
version: "3.9"

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    hostname: 3x-ui
    volumes:
        - ./db/:/etc/x-ui/
    environment:
        XRAY_VMESS_AEAD_FORCED: "false"
    restart: always
    ports:
        - "443:443"
    network_mode: host
    tty: true
    # networks:
    #     - caddy
    # labels:
    #     caddy.@denied.not: ${ALLOWEDIP}
    #     caddy.abort: "@denied"
    #     caddy: ${PANELDOMAIN}
    #     caddy.reverse_proxy: "{{upstreams http 2053}}"
