---
- name: Check if VirtualBox GuestAdditions are installed
  ansible.windows.win_shell: |
    if (Get-Service -Name VBoxService -ErrorAction SilentlyContinue) {
      Write-Output "VirtualBox GuestAdditions are already installed"
      exit 0
    } else {
      Write-Output "VirtualBox GuestAdditions are not installed"
      exit 1
    }
  register: vbox_check
  changed_when: false
  failed_when: false
  tags:
    - vbox_guestadditions

- name: Set default VirtualBox version if not provided
  set_fact:
    vbox_version: "{{ vbox_host_version | default('7.1.6') }}"
  tags:
    - vbox_guestadditions

- name: Display VirtualBox version being used
  debug:
    msg: "Using VirtualBox version {{ vbox_version }} for GuestAdditions"
  tags:
    - vbox_guestadditions

- name: Download VirtualBox GuestAdditions ISO
  ansible.windows.win_get_url:
    url: 'https://download.virtualbox.org/virtualbox/{{ vbox_version }}/VBoxGuestAdditions_{{ vbox_version }}.iso'
    dest: 'C:\Windows\Temp\VBoxGuestAdditions.iso'
  when: vbox_check.rc != 0
  tags:
    - vbox_guestadditions

- name: Mount ISO
  ansible.windows.win_shell: |
    $mountResult = Mount-DiskImage -ImagePath 'C:\Windows\Temp\VBoxGuestAdditions.iso' -PassThru
    $driveLetter = ($mountResult | Get-Volume).DriveLetter
    Write-Output $driveLetter
  register: iso_mount
  when: vbox_check.rc != 0
  tags:
    - vbox_guestadditions

- name: Install VirtualBox GuestAdditions
  ansible.windows.win_shell: |
    $driveLetter = "{{ iso_mount.stdout | trim }}"
    Start-Process -FilePath "$($driveLetter):\VBoxWindowsAdditions.exe" -ArgumentList "/S" -Wait
  when: vbox_check.rc != 0 and iso_mount.stdout | trim != ""
  tags:
    - vbox_guestadditions

- name: Unmount ISO
  ansible.windows.win_shell: |
    Dismount-DiskImage -ImagePath 'C:\Windows\Temp\VBoxGuestAdditions.iso'
  when: vbox_check.rc != 0 and iso_mount.stdout | trim != ""
  tags:
    - vbox_guestadditions

- name: Remove ISO file
  ansible.windows.win_file:
    path: 'C:\Windows\Temp\VBoxGuestAdditions.iso'
    state: absent
  when: vbox_check.rc != 0
  tags:
    - vbox_guestadditions