#cloud-config
# Configuration files for golden VM template

write_files:
  # Micro editor config
  - path: /home/dev/.config/micro/settings.json
    owner: dev:dev
    permissions: "0644"
    content: |
      {
        "clipboard": "terminal",
        "mkparents": true
      }
    defer: true

