#cloud-config
# Configuration files for golden VM template

write_files:
  # Micro editor config
  - path: /home/dev/.config/micro/settings.json
    owner: dev:dev
    permissions: "0644"
    content: |
      {
        "clipboard": "terminal",
        "mkparents": true
      }
    defer: true

  # SSH configuration
  - path: /etc/ssh/sshd_config.d/50-cloud-init.conf
    content: |
      PasswordAuthentication yes
      PubkeyAuthentication yes
      MaxSessions 10
    permissions: "0644"

  # Network MTU fix for Mullvad VPN VMs
  - path: /etc/netplan/66-mtu-fix.yaml
    content: |
      network:
        version: 2
        ethernets:
          "eth*":
            dhcp4: true
            dhcp6: true
            mtu: 1360
          "enp*":
            dhcp4: true
            dhcp6: true
            mtu: 1360
          "ens*":
            dhcp4: true
            dhcp6: true
            mtu: 1360
    permissions: '0600'

  # Welcome README
  - path: /home/dev/Desktop/README.md
    permissions: "0644"
    owner: dev:dev
    defer: true
    content: |
      Welcome!

      To mount shared folders:
      
      ```bash
      sudo mount -t virtiofs folder1 ~/folder1
      ```

      To persist it:
        
      ```bash
      echo "folder1 /home/dev/folder1 virtiofs defaults 0 0" | sudo tee -a /etc/fstab
      ```
