#cloud-config
# Application installation and setup for golden VM template

runcmd:
  # Update package lists after adding repositories
  - apt-get update

  # Install applications from external repositories
  # Note: --allow-downgrades needed for Firefox PPA downgrade from snap version
  - |
    apt-get install -y --allow-downgrades \
      broot \
      warp-terminal \
      codium \
      sourcegit \
      firefox

  # Setup Flathub
  - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  # Install Flatpak applications
  - flatpak install org.kde.kate --assumeyes
