#cloud-config
# Application installation and setup for golden VM template

runcmd:
  # Update package lists after adding repositories
  - apt-get update

  # Install applications from external repositories
  # Note: --allow-downgrades needed for Firefox PPA downgrade from snap version
  - |
    apt-get install -y --allow-downgrades \
      broot \
      docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin \
      warp-terminal \
      codium \
      sourcegit \
      firefox

  # Setup Flathub
  - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  # Install Flatpak applications
  - flatpak install org.kde.kate --assumeyes

  # Note: Docker service and user group setup moved to post-reboot stage
  # This ensures the service files exist and user environment is properly configured
