#cloud-config
# Final commands - Pre-reboot setup
# Note: Post-reboot items (Docker setup, zRAM, user services) are handled by 98-post-reboot.yml

runcmd:
  # Enable and configure essential services
  - systemctl enable --now qemu-guest-agent
  - systemctl set-default graphical.target
  
  # Set micro as default editor
  - chown -R dev:dev /home/dev # chown home
  - echo 'export EDITOR=micro' >> /home/dev/.bashrc
  - echo 'export EDITOR=micro' >> /home/dev/.profile
  - update-alternatives --install /usr/bin/editor editor /usr/bin/micro 100
  - update-alternatives --set editor /usr/bin/micro

  # Fix ownership of user files (final chown before reboot)
  - chown -R dev:dev /home/dev

  # Again update and upgrade
  - apt-get update
  - apt-get upgrade -y

  # Final reboot to activate new kernel and trigger post-reboot setup
  - reboot
