#cloud-config
# Final commands

runcmd:
  # Enable and configure services
  - systemctl enable --now qemu-guest-agent
  - systemctl set-default graphical.target


  # Initialize shell configuration files
  - touch /home/dev/.profile
  - touch /home/dev/.bashrc
  
  # Set micro as default editor
  - chown -R dev:dev /home/dev # chown home
  - echo 'export EDITOR=micro' >> /home/dev/.bashrc
  - echo 'export EDITOR=micro' >> /home/dev/.profile
  - update-alternatives --install /usr/bin/editor editor /usr/bin/micro 100
  - update-alternatives --set editor /usr/bin/micro

  # Install and configure broot function
  - chown -R dev:dev /home/dev # chown home
  - su - dev -c 'printf "y\n" | broot --install || true'

  # Install Claude CLI locally
  - chown -R dev:dev /home/dev # chown home
  - su - dev -c 'mkdir -p /home/dev/.claude/local'
  - su - dev -c 'cd /home/dev/.claude/local && npm i @anthropic-ai/claude-code'
  - su - dev -c 'echo "#!/bin/bash" >> /home/dev/.claude/local/claude'
  - su - dev -c 'echo "exec \"/home/dev/.claude/local/node_modules/.bin/claude\" \"\$@\"" >> /home/dev/.claude/local/claude'
  - su - dev -c 'chmod +x /home/dev/.claude/local/claude'

  # Setup Node.js package managers
  - npm install -g corepack@latest
  - /usr/local/bin/corepack enable
  - /usr/local/bin/corepack prepare yarn@stable --activate
  - /usr/local/bin/corepack prepare pnpm@latest-10 --activate

  # Install Volta node manager (works alongside system Node.js)
  # Volta allows per-project Node.js versions while keeping system Node.js available
  # Use 'volta pin node@version' in project directories to set specific versions
  - chown -R dev:dev /home/dev # chown home
  - su - dev -c 'curl https://get.volta.sh | bash'
  - su - dev -c '$HOME/.volta/bin/volta setup'
  
  # Install latest LTS Node.js via Volta (alongside system Node.js)
  - chown -R dev:dev /home/dev # chown home
  - su - dev -c 'source /home/dev/.bashrc && /home/dev/.volta/bin/volta install node@lts'
  - su - dev -c 'source /home/dev/.bashrc && /home/dev/.volta/bin/volta install npm@latest'
  - su - dev -c 'source /home/dev/.bashrc && /home/dev/.volta/bin/volta install pnpm@latest'
  - su - dev -c 'source /home/dev/.bashrc && /home/dev/.volta/bin/volta install yarn@latest'

  # Python development tools
  - pipx ensurepath
  - pipx install uv

  # Add Claude alias
  - echo 'alias claude="~/.claude/local/claude"' >> '/home/dev/.bashrc'
  - echo 'alias claude="~/.claude/local/claude"' >> '/home/dev/.profile'

  # Enable Playwright MCP service for user session
  - su - dev -c 'systemctl --user enable --now playwright-mcp.service'

  # Fix ownership of user files
  - chown -R dev:dev /home/dev

  # Enable docker arm64 emulation
  - docker run --privileged --rm tonistiigi/binfmt --install arm64
  - docker buildx ls || docker buildx create --use

  # Final reboot to ensure all changes take effect
  - reboot