services:

  database:
    image: mariadb:10.5
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./pterodactyl/database:/var/lib/mysql"
    expose:
      - "3306"
    environment:
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"

  cache:
    image: redis:alpine
    restart: unless-stopped

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: unless-stopped
    links:
      - database
      - cache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./pterodactyl/var/:/app/var/"
      - "./pterodactyl/nginx/:/etc/nginx/http.d/"
      - "./pterodactyl/certs/:/etc/letsencrypt/"
      - "./pterodactyl/logs/:/app/storage/logs"
    environment:
      #      APP_URL: "https://panel.kunet.dev"
      APP_TIMEZONE: "${APP_TIMEZONE}"
      APP_SERVICE_AUTHOR: "noreply@example.com"
      DB_PASSWORD: "${MYSQL_PASSWORD}"
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"

  wings:
    image: ghcr.io/pterodactyl/wings:latest
    restart: always
    ports:
      - "8080:8080"
      - "2022:2022"
    tty: true
    environment:
      TZ: "${APP_TIMEZONE}"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/pterodactyl/:/etc/pterodactyl/"
      - "/var/lib/pterodactyl/:/var/lib/pterodactyl/"
      - "/var/log/pterodactyl/:/var/log/pterodactyl/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
