#cloud-config

chpasswd:
  list: |
    ubuntu:ubuntu
  expire: false

ssh_pwauth: true

runcmd:
  - systemctl restart sshd
  - sudo sed -i 's|ubuntu ALL=(ALL).*|ubuntu ALL=(ALL) ALL|g' /etc/sudoers.d/90*