- name: Test PING.
  hosts: all
  tasks:
    - name: ping
      win_ping:
      tags: win

    - name: Set the default shell to PowerShell
      win_regedit:
        path: HKLM:\SOFTWARE\OpenSSH
        name: DefaultShell
        data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        type: string
        state: present
      tags: win
