services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres-container
    expose:
      - '${POSTGRES_PORT}'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=${LOBE_DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      internal_net:

  minio:
    image: minio/minio
    container_name: lobe-minio-container
    expose:
      - '${MINIO_API_PORT}'
      - '${MINIO_CONSOLE_PORT}'
    volumes:
      - './s3_data:/etc/minio/data'
    environment:
      - 'MINIO_ROOT_USER=${MINIO_ROOT_USER}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}'
      - 'MINIO_DOMAIN=https://${MAIN_DOMAIN}:${MINIO_API_PORT}'
      - 'MINIO_API_CORS_ALLOW_ORIGIN=${APP_URL}'
      - 'MINIO_BROWSER_REDIRECT_URL=https://${MAIN_DOMAIN}:${MINIO_API_PORT}'
    restart: unless-stopped
    command: >
      server /etc/minio/data --address ":${MINIO_API_PORT}" --console-address ":${MINIO_CONSOLE_PORT}"
    networks:
      caddy_net:
      internal_net:

  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-app-container
    expose:
      - '${LOBE_PORT}'
    depends_on:
      - postgresql
      - minio
    environment:
      - 'NEXTAUTH_URL=${APP_URL}/api/auth/callback/authelia'
      - 'DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@lobe-postgres-container:${POSTGRES_PORT}/${LOBE_DB_NAME}'
      - 'S3_ENABLE_PATH_STYLE=1'
      - 'S3_ENDPOINT=http://lobe-minio-container${MINIO_API_PORT}'
      - 'S3_PUBLIC_DOMAIN=https://${MAIN_DOMAIN}:${MINIO_API_PORT}'
    env_file:
      - .env
    restart: unless-stopped
    networks:
      caddy_net:
      internal_net:
  
networks:
  caddy_net:
    external: true
  internal_net:

volumes:
  data:
    driver: local
  s3_data:
    driver: local
