services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres-container
    expose:
      - '${POSTGRES_PORT}'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=${LOBE_DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: lobe-minio-container
    expose:
      - '${MINIO_API_PORT}'
      - '${MINIO_CONSOLE_PORT}'
    volumes:
      - './s3_data:/etc/minio/data'
    environment:
      - 'MINIO_ROOT_USER=${MINIO_ROOT_USER}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}'
#      - 'MINIO_DOMAIN=lobe-s3-api.example.com' # TODO
      - 'MINIO_API_CORS_ALLOW_ORIGIN=${LOBECHAT_DOMAIN}' # TODO
    restart: unless-stopped
    command: >
      server /etc/minio/data --address ":${MINIO_API_PORT}" --console-address ":${MINIO_CONSOLE_PORT}"

  logto:
    image: svhd/logto
    container_name: lobe-logto-container
    expose:
      - '${LOGTO_PORT}'
      - '${LOGTO_ADMIN_PORT}'
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - 'TRUST_PROXY_HEADER=1'
      - 'DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@lobe-postgres-container:${POSTGRES_PORT}/logto'
      - 'ENDPOINT=${APP_URL}'
      - 'ADMIN_ENDPOINT=http://localhost:${LOGTO_ADMIN_PORT}'
    entrypoint: [ 'sh', '-c', 'npm run cli db seed -- --swe && npm start' ]


  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-app-container
    expose:
      - '${LOBE_PORT}'
    depends_on:
      - postgresql
      - minio
      - logto
    environment:
      - 'NEXT_AUTH_SSO_PROVIDERS=logto'
      - 'KEY_VAULTS_SECRET=${KEY_VAULTS_SECRET}'
      - 'NEXT_AUTH_SECRET=${NEXT_AUTH_SECRET}'
      - 'DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@lobe-postgres-container:${POSTGRES_PORT}/${LOBE_DB_NAME}'
      - 'LOGTO_ISSUER=http://lobe-logto-container:${LOGTO_PORT}/oidc'
      - 'S3_BUCKET=${MINIO_LOBE_BUCKET}'
      - 'S3_ENABLE_PATH_STYLE=1'
      - 'S3_ENDPOINT=http://lobe-minio-container${MINIO_API_PORT}'
    env_file:
      - .env
    restart: unless-stopped
  
  
networks:
  caddy_net:
    external: true

volumes:
  data:
    driver: local
  s3_data:
    driver: local
