services:
  minio:
    image: minio/minio
    container_name: minio-container
    expose:
      - '${MINIO_API_PORT}'
      - '${MINIO_CONSOLE_PORT}'
    volumes:
      - './s3_data:/etc/minio/data'
    environment:
      - 'MINIO_ROOT_USER=${MINIO_ROOT_USER}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}'
      - 'MINIO_DOMAIN=https://${MINIO_API_DOMAIN}'
      - 'MINIO_API_CORS_ALLOW_ORIGIN=${APP_URL}' #todo
    restart: unless-stopped
    command: >
      server /etc/minio/data --address ":${MINIO_API_PORT}" --console-address ":${MINIO_CONSOLE_PORT}"
    networks:
      caddy_net:

networks:
  caddy_net:
    external: true

volumes:
  s3_data:
    driver: local
