- name: Get current shell
  win_reg_stat:
    path: HKLM:\SOFTWARE\OpenSSH
    name: DefaultShell
  register: current_shell

- name: Print current shell
  debug:
    msg: "{{ current_shell }}"

- name: Set the default shell to PowerShell
  win_regedit:
    path: HKLM:\SOFTWARE\OpenSSH
    name: DefaultShell
    data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    type: string
    state: present
  when: not current_shell.exists or current_shell.value.find('powershell') == -1
